### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by pana-cc** [testdeck/testdeck#171]
What we can do to establish the testdeck in place of mocha-typescript and boost adoption in general. Here are some ideas, we can split them into sub-issues if we decide to pursue them.

 - [ ] Design Logo
 - [ ] Consider designing swag:
    - [ ] Stickies
    - [ ] T-shirts
 - [ ] Update the [mocha wiki](https://github.com/mochajs/mocha/wiki), this is an awesome traction channel, it is the only place where I've added a link to mocha-typescript
 - [ ] Add "Backers", list contributors and individuals sponsors.
 - [ ] Add "Sponsors", cross link this with sponsor company pages and logos.
 - [ ] Decide if we will actually accept "money", if we do
    - [ ] Nurture contributions by sending swag
    - [ ] Pay "influencers" for blog posts
 - [ ] Build a site, mocha-typescript.org was somewhat ok, run google analytics
    - [ ] Do we need anything more than GitHub pages?
 - [ ] Social marketing - Twitter?
 - [ ] Other traction channels? Read [Traction](https://www.amazon.com/Traction-Startup-Achieve-Explosive-Customer/dp/1591848369/ref=sr_1_2?keywords=traction&qid=1551545379&s=books&sr=1-2)
 - [ ] Life presence, organize local communities, talk
 - [ ] Content marketing? Read [The Story Engine](https://www.amazon.com/Story-Engine-entrepreneurs-strategy-storytelling-ebook/dp/B0722TR5LX/ref=sr_1_1_sspa?keywords=The+Story+Engine&qid=1551545501&s=gateway&sr=8-1-spons&psc=1)
   - [ ] Content Strategy
   - [ ] Content Calendar
   - [ ] Leads
   - [ ] WTF do we do with emails?
   - [ ] Can we even produce content?

**Comment by silkentrance** [comment]
For testdeck/jest we should try to get into the loop by contacting these projects

- https://github.com/kulshekhar/ts-jest
- https://jestjs.io/docs/en/getting-started.html#using-typescript

**Comment by silkentrance** [comment]
For the karma support, we should try to get into the loop by contacting these projects

- https://www.npmjs.com/package/karma-typescript
- https://github.com/karma-runner/karma-mocha
- https://github.com/karma-runner/karma-jasmine (for a future testdeck/jasmine)

testdeck/jest in combination with karma is still somewhat complicated

- https://github.com/facebook/jest/issues/1643

**Comment by silkentrance** [comment]
For a future testdeck/jasmine, we should try to get into the loop by contacting these projects

- https://github.com/jasmine/jasmine

**Comment by silkentrance** [comment]
let's move this to the organisation level...

**Comment by silkentrance** [comment]
Some ideas on unique selling points for testdeck

- ease of migration between test frameworks
  (can be as simple as replacing the `@testdeck/xxx` dependency)

**Comment by silkentrance** [comment]
~~Will move this to top level as it encompasses all testdeck marketing activities.~~

this is not how github works... *sigh*
