### ISSUE TITLE
Technical Debt

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck#186]
### Documentation

 - [x] Readme for each integration: jest, mocha, jasmine.
 - [x] Readme for each seed: jest, mocha, jasmine.
 - [x] Update the docs. See [testdeck/testdeck-site](/testdeck/testdeck-site)
 - [ ] proper API documentation in core

### Missing Functionality

 - [x] skipOnError - was scrapped from the API
   mocha only, maybe jasmine, never jest or similar such testing frameworks
 - [ ] Watcher? Move it into separate package, remove it from @testdeck/mocha. Make it configurable to run mocha/jest/jasmine after tsc change detection.

### Refactoring

 - [x] Continue the refactoring, split the big class in core into smaller classes (just keep them in the same file, I kind of get lost when the code is moved into smaller files, idk I am used to folding code) Overall this should be relatively safe since there is a decent unit test coverage in core, the tests there run for few seconds, so iterations should be fast.
   - ATM i do not see any more need for that

### Testing

 - [ ] Integration tests are ignored at this point, we need to pick 1-2 tests with "only" and 1-2 of the most extensive suites. I think with the new unit tests in place the old way of testing 100% coverage with end-to-end tests is a bit excessive. They used to take long. Maybe now we can take a smaller subset that will execute faster. Also the integration tests does not need to pack and install, we can rely on lerna to symlink what is necessary into the integration tests.
 - [ ] Watcher tests.

### Browser Integration may have been lost in translation #181, #157 (reopened)

 - [ ] karma #112
 - [ ] webpack #114 

### Publishing Packages on NPM

 - [x] Lerna publish failed on private packages (the seeds/*) maybe there is a way to list just the @testdeck/* as publishable

**Comment by silkentrance** [comment]
I have removed the gitmodules so that lerna publish will succeed.

We have to provide tests for each seed.

**Comment by pana-cc** [comment]
We will reopen issues as we see fit. I am going to clean up the issues a bit.
