### ISSUE TITLE
Going for 1.0.0 release

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck#244]
To my reckoning there are no more serious flaws in the software, so we should definitely go for a 1.0.0 release.

In the wake of the release, we should also deprecate mocha-typescript, redirecting users to the new ``@testdeck/mocha`` package.

## Preventing Issues

- [x] #245 (temporarily fixed, needs more work)
- [x] #254 (should fix the temporary fix for #245, needs further investigation)
- [x] #235 (source maps)
- [ ] #255
- [ ] #256 (test coverage and quality)
- [ ] (include DI test cases for all supported test frameworks)
- [ ] (include @param tests for all supported test frameworks)
- [ ] (include both non-async, async and callback based test cases for all supported test frameworks, where supported)
- [ ] #302 (new central documentation)
- [ ] (all di/test framework packages' documentation link to the central documentation)
- [ ] #310 (maybe improve upon DI if possible)
- [ ] (add more DI framework support, e.g. [inversify](https://inversify.io/))
- [ ] (rework all testdeck feeds to match our then set up, linking to the correct documentation and packages etc.)

**Comment by silkentrance** [comment]
@PanayotCankov how can we deprecate the mocha-typescript package from npm and point it towards ``@testdeck/mocha`` instead?

**Comment by zveljkovic** [comment]
I have just created one issue that I would consider serious flaw...
https://github.com/testdeck/testdeck/issues/246

**Comment by silkentrance** [comment]
@zveljkovic Yes, that is a very good one. Thank you very much for that.

**Comment by silkentrance** [comment]
Serious flaws

- #245 (temporarily fixed, needs more work)
- #254 (should fix the temporary fix for #245, needs further investigation)

**Comment by silkentrance** [comment]
I have locked this so that we can keep this focused.

We will decide which issue is preventing the 1.0.0 release.

**Comment by pana-cc** [comment]
I think we have good enough coverage and I think we ship maps now. Maybe this is ready to 🚀

**Comment by silkentrance** [comment]
🚀

**Comment by silkentrance** [comment]
closing as we need to reconsider
